# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ae1eccb52dda3deee2dfe5fde5beb9e031fd9c4427ed168aa29812375ccc376331f9de25dd50a7e02136e5e23f5e73ff5b44664c699c4d801431c55d245a35

test:
  secret_key_base: a1718ce18cfb1fde4924971e5033c50715773fe93a2429a61593f3462ace43271b42d1bb4a50a8e9d326c4095c8cba9d6827803cad50dae2bdfd08c2ed66c6f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
